//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVGTest {
    
    
    public partial class UC {
        
        /// <summary>
        /// mySvg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.Svg mySvg;
        
        /// <summary>
        /// house control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.Group house;
        
        /// <summary>
        /// Rectangle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.Rectangle Rectangle1;
        
        /// <summary>
        /// PolyLine1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.PolyLine PolyLine1;
        
        /// <summary>
        /// PolyLine2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.PolyLine PolyLine2;
        
        /// <summary>
        /// Ellipse1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.Ellipse Ellipse1;
        
        /// <summary>
        /// MyPath control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.Path MyPath;
        
        /// <summary>
        /// Path2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.Path Path2;
        
        /// <summary>
        /// Use1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.Use Use1;
        
        /// <summary>
        /// Use2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotM.Html5.SVG.Use Use2;
    }
}
